"use client";

import { useState } from "react";
import DocumentationList from "./components/DocumentationList";
import PdfViewer from "../components/PdfViewer";

export default function DocumentationPage() {
  const [selectedDoc, setSelectedDoc] = useState(null);

  return (
    <div className="p-6">
      {/* PAGE TITLE */}
      <h1 className="text-2xl font-bold mb-6">Documentation</h1>

      {/* OVERVIEW SECTION — KEEPING YOUR EXISTING STRUCTURE */}
      <div className="mb-8 p-4 bg-gray-100 rounded shadow">
        <h2 className="text-xl font-semibold mb-3">Overview of All Documents</h2>

        <ul className="list-disc pl-6 space-y-2 text-gray-700">
          <li><strong>Backend & Frontend Architecture:</strong> How FastAPI and Next.js communicate.</li>
          <li><strong>Biosensing Platform Documentation:</strong> High-level system overview.</li>
          <li><strong>Course Outline — Fullstack API Engineering:</strong> Course modules and structure.</li>
          <li><strong>General Auth Token Access System:</strong> Token lifecycle and security.</li>
          <li><strong>Main.py Documentation:</strong> App creation, router mounting, middleware.</li>
          <li><strong>ML Models Folder Structure:</strong> Organization and naming conventions.</li>
          <li><strong>Payment System Architecture:</strong> Payment flow and external integrations.</li>
          <li><strong>Router Documentation:</strong> All FastAPI routers and responsibilities.</li>
          <li><strong>Swagger Documentation:</strong> How autogenerated API docs map to routes.</li>
          <li><strong>Token-Based Access System:</strong> Roles, permissions, and access control.</li>
        </ul>
      </div>

      {/* MAIN DOCUMENTATION LAYOUT */}
      <div className="flex gap-6">
        {/* LEFT SIDE — DOCUMENT LIST */}
        <div className="w-1/3">
          <DocumentationList onSelect={setSelectedDoc} />
        </div>

        {/* RIGHT SIDE — PDF VIEWER */}
        <div className="w-2/3">
          <PdfViewer doc={selectedDoc} />
        </div>
      </div>
    </div>
  );
}
