"use client";

import { useState } from "react";

type DocumentationItem = {
  title: string;
  url: string;
};

function PdfViewer({ doc }: { doc: DocumentationItem | null }) {
  if (!doc) {
    return (
      <div className="flex h-[600px] items-center justify-center rounded border bg-gray-50 text-gray-500">
        Select a document to view it.
      </div>
    );
  }

  return (
    <iframe
      title={doc.title}
      src={doc.url}
      className="h-[600px] w-full rounded border"
    />
  );
}

const documents: DocumentationItem[] = [
  {
    title: "Backend & Frontend Architecture",
    url: "https://your-vercel-blob-url/backend-frontend-architecture.pdf",
  },
  {
    title: "Biosensing Platform Documentation",
    url: "https://your-vercel-blob-url/biosensing-platform.pdf",
  },
  {
    title: "Course Outline — Fullstack API Engineering",
    url: "https://your-vercel-blob-url/fullstack-api-engineering.pdf",
  },
  {
    title: "General Auth Token Access System",
    url: "https://your-vercel-blob-url/general-auth-token-access-system.pdf",
  },
  {
    title: "Main.py Documentation",
    url: "https://your-vercel-blob-url/main-py-documentation.pdf",
  },
  {
    title: "ML Models Folder Structure",
    url: "https://your-vercel-blob-url/ml-models-folder-structure.pdf",
  },
  {
    title: "Payment System Architecture",
    url: "https://your-vercel-blob-url/payment-system-architecture.pdf",
  },
  {
    title: "Router Documentation",
    url: "https://your-vercel-blob-url/router-documentation.pdf",
  },
  {
    title: "Swagger Documentation",
    url: "https://your-vercel-blob-url/swagger-documentation.pdf",
  },
  {
    title: "Token-Based Access System",
    url: "https://your-vercel-blob-url/token-based-access-system.pdf",
  },
];

function DocumentationList({
  onSelect,
}: {
  onSelect: (document: DocumentationItem) => void;
}) {
  return (
    <div className="space-y-2">
      {documents.map((document) => (
        <button
          key={document.url}
          type="button"
          onClick={() => onSelect(document)}
          className="block w-full rounded border bg-white p-3 text-left hover:bg-gray-50"
        >
          {document.title}
        </button>
      ))}
    </div>
  );
}

export default function DocumentationPage() {
  const [selectedDoc, setSelectedDoc] = useState<DocumentationItem | null>(null);

  return (
    <div className="p-6">
      <h1 className="text-2xl font-bold mb-6">Documentation</h1>

      <div className="mb-8 p-4 bg-gray-100 rounded shadow">
        <h2 className="text-xl font-semibold mb-3">Overview of All Documents</h2>

        <ul className="list-disc pl-6 space-y-2 text-gray-700">
          <li><strong>Backend & Frontend Architecture:</strong> How FastAPI and Next.js communicate.</li>
          <li><strong>Biosensing Platform Documentation:</strong> High-level system overview.</li>
          <li><strong>Course Outline — Fullstack API Engineering:</strong> Course modules and structure.</li>
          <li><strong>General Auth Token Access System:</strong> Token lifecycle and security.</li>
          <li><strong>Main.py Documentation:</strong> App creation, router mounting, middleware.</li>
          <li><strong>ML Models Folder Structure:</strong> Organization and naming conventions.</li>
          <li><strong>Payment System Architecture:</strong> Payment flow and external integrations.</li>
          <li><strong>Router Documentation:</strong> All FastAPI routers and responsibilities.</li>
          <li><strong>Swagger Documentation:</strong> How autogenerated API docs map to routes.</li>
          <li><strong>Token-Based Access System:</strong> Roles, permissions, and access control.</li>
        </ul>
      </div>

      <div className="flex gap-6">
        <div className="w-1/3">
          <DocumentationList onSelect={setSelectedDoc} />
        </div>

        <div className="w-2/3">
          <PdfViewer doc={selectedDoc} />
        </div>
      </div>
    </div>
  );
}
