"use client";

import { useState } from "react";

type DocumentationItem = {
  title: string;
  file: string;
};

function PdfViewer({ doc }: { doc: DocumentationItem | null }) {
  if (!doc) {
    return (
      <div className="flex h-[600px] items-center justify-center rounded border bg-gray-50 text-gray-500">
        Select a document to view it.
      </div>
    );
  }

  return (
    <iframe
      title={doc.title}
      src={`/documents/${doc.file}`}
      className="h-[600px] w-full rounded border"
    />
  );
}

const documents: DocumentationItem[] = [
  { title: "Backend & Frontend Architecture", file: "backend-frontend-architecture.pdf" },
  { title: "Biosensing Platform Documentation", file: "biosensing-platform.pdf" },
  { title: "Course Outline — Fullstack API Engineering", file: "fullstack-api-engineering.pdf" },
  { title: "General Auth Token Access System", file: "general-auth-token-access-system.pdf" },
  { title: "Main.py Documentation", file: "main-py-documentation.pdf" },
  { title: "ML Models Folder Structure", file: "ml-models-folder-structure.pdf" },
  { title: "Payment System Architecture", file: "payment-system-architecture.pdf" },
  { title: "Router Documentation", file: "router-documentation.pdf" },
  { title: "Swagger Documentation", file: "swagger-documentation.pdf" },
  { title: "Token-Based Access System", file: "token-based-access-system.pdf" },
];

function DocumentationList({
  onSelect,
}: {
  onSelect: (document: DocumentationItem) => void;
}) {
  return (
    <div className="space-y-2">
      {documents.map((document) => (
        <button
          key={document.file}
          type="button"
          onClick={() => onSelect(document)}
          className="block w-full rounded border bg-white p-3 text-left hover:bg-gray-50"
        >
          {document.title}
        </button>
      ))}
    </div>
  );
}

export default function DocumentationPage() {
  const [selectedDoc, setSelectedDoc] = useState<DocumentationItem | null>(null);

  return (
    <div className="p-6">
      {/* PAGE TITLE */}
      <h1 className="text-2xl font-bold mb-6">Documentation</h1>

      {/* OVERVIEW SECTION — KEEPING YOUR EXISTING STRUCTURE */}
      <div className="mb-8 p-4 bg-gray-100 rounded shadow">
        <h2 className="text-xl font-semibold mb-3">Overview of All Documents</h2>

        <ul className="list-disc pl-6 space-y-2 text-gray-700">
          <li><strong>Backend & Frontend Architecture:</strong> How FastAPI and Next.js communicate.</li>
          <li><strong>Biosensing Platform Documentation:</strong> High-level system overview.</li>
          <li><strong>Course Outline — Fullstack API Engineering:</strong> Course modules and structure.</li>
          <li><strong>General Auth Token Access System:</strong> Token lifecycle and security.</li>
          <li><strong>Main.py Documentation:</strong> App creation, router mounting, middleware.</li>
          <li><strong>ML Models Folder Structure:</strong> Organization and naming conventions.</li>
          <li><strong>Payment System Architecture:</strong> Payment flow and external integrations.</li>
          <li><strong>Router Documentation:</strong> All FastAPI routers and responsibilities.</li>
          <li><strong>Swagger Documentation:</strong> How autogenerated API docs map to routes.</li>
          <li><strong>Token-Based Access System:</strong> Roles, permissions, and access control.</li>
        </ul>
      </div>

      {/* MAIN DOCUMENTATION LAYOUT */}
      <div className="flex gap-6">
        {/* LEFT SIDE — DOCUMENT LIST */}
        <div className="w-1/3">
          <DocumentationList onSelect={setSelectedDoc} />
        </div>

        {/* RIGHT SIDE — PDF VIEWER */}
        <div className="w-2/3">
          <PdfViewer doc={selectedDoc} />
        </div>
      </div>
    </div>
  );
}
